title: www.templer.se
email: sven.templer(at)gmail.com
description: > 
  Welcome to my personal website!
baseurl: "" 
url: "http://www.templer.se" 
permalink: /blog/:year/:month/:day/:title
twitter_username: setempler
github_username:  setempler
collections:
  manuals:
    permalink: /manuals/:title
    output: true


# Build settings
markdown: kramdown

gems:
  - jekyll-gist
