# build

permalink: /blog/:year-:month-:day/:title
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids: true
gems: [jekyll-paginate, jekyll-gist]
paginate: 3
paginate_path: "/blog/page/:num"
sass:
  sass_dir: _scss
  style: compressed # or 'expanded'
navbar:
  - slug: about
    title: about
  - slug: blog
    title: blog
  - slug: code
    title: code
  - slug: manuals
    title: manuals
collections:
  manuals:
    permalink: /manuals/:title
    output: true
exclude:
  - "*.Rmd"
#safe: true
#lsi: false

# about

title: www.templer.se
email: sven.templer(at)gmail.com
url: "http://www.templer.se"
baseurl: ""
repo: http://github.com/setempler/setempler.github.io
author:
  name: Sven E. Templer
  job: Data Scientist
  bio: "Loving statistics, genomes and strawberries."
  thumb: /images/avatar.png
  email: sven.templer@gmail.com
  url: http://www.templer.se
  github: https://github.com/setempler
  twitter: https://twitter.com/setempler
