# general
title: www.templer.se
email: sven.templer(at)gmail.com
description: >
  Welcome to my personal website!
twitter_username: setempler
github_username:  setempler
url: "http://www.templer.se"
baseurl: ""

# blog
permalink: /blog/:year-:month-:day/:title

# collections
collections:
  manuals:
    permalink: /manuals/:title
    output: true


# Build settings
markdown: kramdown

gems:
  - jekyll-gist
